### ISSUE TITLE
malformed yaml file causes courier to blowup

### ISSUE THREAD

**Issue by scoheb** [operator-framework/operator-courier#16]
Purposely moved a `-` in a crd.yml file and ran verify:

> [root@0d92433c567b test]# operator-courier verify .
Traceback (most recent call last):
  File "/usr/local/bin/operator-courier", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/operatorcourier/cli.py", line 9, in main
    parser.parse()
  File "/usr/local/lib/python3.6/site-packages/operatorcourier/cli.py", line 35, in parse
    getattr(self, args.command)()
  File "/usr/local/lib/python3.6/site-packages/operatorcourier/cli.py", line 43, in verify
    api.build_and_verify(source_dir=args.source_dir)
  File "/usr/local/lib/python3.6/site-packages/operatorcourier/api.py", line 39, in build_and_verify
    bundle = BuildCmd().build_bundle(yaml_files)
  File "/usr/local/lib/python3.6/site-packages/operatorcourier/build.py", line 30, in build_bundle
    bundle = self._updateBundle(bundle, item)
  File "/usr/local/lib/python3.6/site-packages/operatorcourier/build.py", line 19, in _updateBundle
    operatorBundle["data"][self._get_field_entry(yamlContent)].append(yaml.safe_load(yamlContent))
  File "/usr/local/lib/python3.6/site-packages/operatorcourier/build.py", line 15, in _get_field_entry
    yaml_type = identify.get_operator_artifact_type(yamlContent)
  File "/usr/local/lib/python3.6/site-packages/operatorcourier/identify.py", line 9, in get_operator_artifact_type
    operatorArtifact = yaml.safe_load(operatorArtifactString)
  File "/usr/local/lib64/python3.6/site-packages/yaml/__init__.py", line 94, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib64/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/local/lib64/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/local/lib64/python3.6/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/usr/local/lib64/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib64/python3.6/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "<unicode string>", line 9, column 3:
      group: marketplace.redhat.com
      ^
expected <block end>, but found '<block mapping start>'
  in "<unicode string>", line 21, column 5:
        type: string
        ^

I would expect the parsing error to be caught and presented nicely to the user with a non-zero exit code.

**Comment by kevinrizza** [comment]
This issue was resolved by https://github.com/operator-framework/operator-courier/pull/35
