### ISSUE TITLE
operator-courier does not work

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-courier#174]
No matter install what kind of version of `operator-courier`, it always report error in my host as follows:

```console
root@gyliu-dev1:/usr/bin# operator-courier -v
Traceback (most recent call last):
  File "/usr/local/bin/operator-courier", line 7, in <module>
    from operatorcourier.cli import main
  File "/usr/local/lib/python3.5/dist-packages/operatorcourier/cli.py", line 7, in <module>
    from operatorcourier import api
  File "/usr/local/lib/python3.5/dist-packages/operatorcourier/api.py", line 16, in <module>
    from operatorcourier.flatten import flatten_bundles
  File "/usr/local/lib/python3.5/dist-packages/operatorcourier/flatten.py", line 59
    file_paths_to_copy.append((csv_path, f'{basename}-v{version}{ext}'))
                                                                     ^
SyntaxError: invalid syntax
```

```console
root@gyliu-dev1:/usr/bin# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by gyliu513** [comment]
```console
root@gyliu-dev1:~/go/src/github.com/operator-framework# operator-courier push "$OPERATOR_DIR" "$QUAY_NAMESPACE" "$PACKAGE_NAME" "$PACKAGE_VERSION" "$TOKEN"
Traceback (most recent call last):
  File "/usr/local/bin/operator-courier", line 7, in <module>
    from operatorcourier.cli import main
  File "/usr/local/lib/python3.5/dist-packages/operatorcourier/cli.py", line 7, in <module>
    from operatorcourier import api
  File "/usr/local/lib/python3.5/dist-packages/operatorcourier/api.py", line 16, in <module>
    from operatorcourier.flatten import flatten_bundles
  File "/usr/local/lib/python3.5/dist-packages/operatorcourier/flatten.py", line 59
    file_paths_to_copy.append((csv_path, f'{basename}-v{version}{ext}'))
                                                                     ^
SyntaxError: invalid syntax
```

**Comment by MartinBasti** [comment]
You are using old version of python (3.5) Op-courier requires 3.6+

**Comment by gyliu513** [comment]
Thanks @MartinBasti , I created a PR https://github.com/operator-framework/operator-courier/pull/175 to highlight the python version as Prerequisites.

**Comment by MartinBasti** [comment]
It is also in setup.py so pip installation should at least warn you. Did you just cloned repo?

https://github.com/operator-framework/operator-courier/blob/master/setup.py#L30

**Comment by gyliu513** [comment]
There is no error when install via `pip`

```console
root@gyliu-dev1:/usr/bin# pip3 install operator-courier
Collecting operator-courier
  Using cached https://files.pythonhosted.org/packages/8a/3b/c8f3d95ee79a2d4992895b715095fcadeca7145f0b8fd7e5b9dd0ceecf24/operator_courier-2.1.7-py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): semver in /usr/local/lib/python3.5/dist-packages (from operator-courier)
Requirement already satisfied (use --upgrade to upgrade): validators in /usr/local/lib/python3.5/dist-packages (from operator-courier)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/local/lib/python3.5/dist-packages (from operator-courier)
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python3.5/dist-packages (from operator-courier)
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.4.0 in /usr/local/lib/python3.5/dist-packages (from validators->operator-courier)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /usr/local/lib/python3.5/dist-packages (from validators->operator-courier)
Requirement already satisfied (use --upgrade to upgrade): chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests->operator-courier)
Requirement already satisfied (use --upgrade to upgrade): idna<2.9,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests->operator-courier)
Requirement already satisfied (use --upgrade to upgrade): urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests->operator-courier)
Requirement already satisfied (use --upgrade to upgrade): certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests->operator-courier)
Installing collected packages: operator-courier
Successfully installed operator-courier-2.1.7
You are using pip version 8.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by MartinBasti** [comment]
hah, lol, it works in opposite way. Properly errors when using git repo directly.

```
root@py3.5:/# pip install git+https://github.com/operator-framework/operator-courier.git
...
ERROR: Package 'operator-courier' requires a different Python: 3.5.9 not in '>=3.6, <4'
```

Maybe there is a different attribute that should be used for PYPI?

**Comment by MartinBasti** [comment]
Older releases of operator-courier have incorrect requirements. `pip install operator-courier` just install old version
```
pip install operator-courier==2.1.7
ERROR: Could not find a version that satisfies the requirement operator-courier==2.1.7 (from versions: 0.0.1, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0)
ERROR: No matching distribution found for operator-courier==2.1.7
```

IMHO those broken releases should be removed from PyPI

**Comment by StykMartin** [comment]
@MartinBasti 
➜   python3.7 -m pip install operator-courier==2.1.7 --user -v

Works for me

**Comment by StykMartin** [comment]
@gyliu513 can you reproduce the same steps with `-v`?
I would like to see the output with `python3.5`

**Comment by MartinBasti** [comment]
@gyliu513 you have an ancient PIP, it doesn't parse requirements correctly
`You are using pip version 8.1.1, however version 19.3.1 is available.`

**Comment by StykMartin** [comment]
> @gyliu513 you have an ancient PIP, it doesn't parse requirements correctly
> `You are using pip version 8.1.1, however version 19.3.1 is available.`

PIP 9.0.0 should help
https://pip.pypa.io/en/stable/news/#id228

**Comment by gyliu513** [comment]
@MartinBasti here are the detail with `-v`

```
root@gyliu-dev1:~# pip3 install operator-courier -v
Converted retries value: Retry(total=5, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=5, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
Converted retries value: Retry(total=5, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=5, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
Collecting operator-courier
  1 location(s) to search for versions of operator-courier:
  * https://pypi.python.org/simple/operator-courier/
  Getting page https://pypi.python.org/simple/operator-courier/
  Starting new HTTPS connection (1): pypi.org
  "GET /simple/operator-courier/ HTTP/1.1" 304 0
  Analyzing links from page https://pypi.org/simple/operator-courier/
    Found link https://files.pythonhosted.org/packages/9e/29/c040617b6e811362e2926e6dc98c2f9ab764c5a16c3eb5d4773804de9c30/operator-courier-0.0.1.tar.gz#sha256=6c04ad557fb5bac99b5ba90fbd97cfc84e8880ad7b28b4d560d31f47498705e9 (from https://pypi.org/simple/operator-courier/), version: 0.0.1
    Found link https://files.pythonhosted.org/packages/2c/04/4bb5048ad1c68759db24be3cf6c998b53c3e82505bd98a3c300e51b33092/operator_courier-0.0.1-py3-none-any.whl#sha256=e6ba4468ece5ce2ecfa59a8154ce59711a4f661077d0bba51921800388d5ae22 (from https://pypi.org/simple/operator-courier/), version: 0.0.1
    Found link https://files.pythonhosted.org/packages/91/62/cf43c66e5d427e561e06635fbeabe867354edaa63dc2fbcb30e22ebefdcc/operator-courier-1.0.0.tar.gz#sha256=6b190fdab602548de54b38aa24ed3dc67fb3de8e24aa6f1c2305985f68184c8c (from https://pypi.org/simple/operator-courier/), version: 1.0.0
    Found link https://files.pythonhosted.org/packages/c8/0f/c47ae9b9de01095fe6ed584b4fa06f3a19f7d00f86de95f8930e279aea7b/operator_courier-1.0.0-py3-none-any.whl#sha256=643752078d13f539d40fc84605955ee1b3b06b65f4e4d0d769e8b546a453293a (from https://pypi.org/simple/operator-courier/), version: 1.0.0
    Found link https://files.pythonhosted.org/packages/ca/25/e087b5825af38c33fd62b9d4529f33fd3fce2feb2ba335c101cd15c6e2b8/operator-courier-1.0.1.tar.gz#sha256=81375c074a0d49b74e08583ced479a697640de9cefe57384f1a4567441d6da09 (from https://pypi.org/simple/operator-courier/), version: 1.0.1
    Skipping link https://files.pythonhosted.org/packages/af/ad/de379026e50b1d15ddd9e0ff7685ee03285ad3bf1641abc8a96e1ecc5e13/operator_courier-1.0.1-py2-none-any.whl#sha256=ce2ba422aed7c924adc4c8e9929c0411db1c318b2f58df39857324e8e5932160 (from https://pypi.org/simple/operator-courier/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/39/c8/e952c83ca4f56c76506beeb1c0e3b47aa180a8b535f072cb8b4b9f346c3c/operator-courier-1.0.2.tar.gz#sha256=65b93bd4ae8fb0464abae131762671784f32b478625935663bab73f270cd2ae9 (from https://pypi.org/simple/operator-courier/), version: 1.0.2
    Skipping link https://files.pythonhosted.org/packages/c0/6a/5d14161ac0b126722a14023227422b7d772d06e10ed67140d10c88322414/operator_courier-1.0.2-py2-none-any.whl#sha256=e6c86475da79d8cac35ff080fc06da93d3533378a8b610cd72a8cd09a298d13a (from https://pypi.org/simple/operator-courier/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/f8/4e/a7fe1ebcacee81bf1edaf9426cae7f2c58a02286b042c589fbddd544d41a/operator-courier-1.1.0.tar.gz#sha256=7de0cdb9304276e99193153d08a9fd0229b8b10542f8aebc9da3a4ab9a1a7051 (from https://pypi.org/simple/operator-courier/), version: 1.1.0
    Skipping link https://files.pythonhosted.org/packages/8c/01/d6a20b906f4034e5768509febd8123075588e3269c55ef3e72add799eb99/operator_courier-1.1.0-py2-none-any.whl#sha256=8a05ab006ecc69de8cc5a01228e08e38c462d3096bad5a28e7ea2ee279532b15 (from https://pypi.org/simple/operator-courier/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/fb/29/66cb7a504f480882667a32e290af7a1a20bd71d0a3fab40be9a81f6955ed/operator-courier-1.2.0.tar.gz#sha256=b081fb982c48686a4ea46f090d09736427a113219a3daef19bf1cb98f62d8abd (from https://pypi.org/simple/operator-courier/), version: 1.2.0
    Skipping link https://files.pythonhosted.org/packages/d0/20/f1deadc3885607dc9912d9f3fd9530142a5f04de3bd169e5eea4aba2a23b/operator_courier-1.2.0-py2-none-any.whl#sha256=04d06077720fb2be6b38c91361ec3014c25dc37fc4196277dd1903d87830c011 (from https://pypi.org/simple/operator-courier/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/67/f7/ec9761dd9e1cb431f58cce5d2feb641b0ed821734b3b2b904d501ad133bb/operator-courier-1.2.1.tar.gz#sha256=5796b43e0275a7c43f2fa860205a5fb4fba4d234b1936f5b4f715cf71964bf21 (from https://pypi.org/simple/operator-courier/), version: 1.2.1
    Skipping link https://files.pythonhosted.org/packages/a9/d2/669298b9cc13feba5379adf4a2cbaefab9531ca20df714d3bac2269dd453/operator_courier-1.2.1-py2-none-any.whl#sha256=b54c3bbefda545f868027fa5d9115e8dd3a54f09d1299cf942a34c279e95dca4 (from https://pypi.org/simple/operator-courier/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/55/dd/e9ea774c511d35984bc2763e30b6d236406634f946c8c34038b5fb457de1/operator-courier-1.3.0.tar.gz#sha256=e66edaf3cc8a682a6a76a70d71e39d6496eaeca5c04a9022f194e96ca840f6d2 (from https://pypi.org/simple/operator-courier/), version: 1.3.0
    Skipping link https://files.pythonhosted.org/packages/b3/9c/6cb57f83c39f75b8290cfd95142f9357fffd43c56a486c01712e37f2c1f7/operator_courier-1.3.0-py2-none-any.whl#sha256=b3cfbdf65b28ee6637a0200cb0761fe89e7aa1caa7ce745922ded6b06422c2f6 (from https://pypi.org/simple/operator-courier/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/35/8d/d25525791b8a5d1ba5b0894455a64a392802323168e2e2114714d7c13afa/operator-courier-2.0.1.tar.gz#sha256=40b8424a9cf7f8ede3cfff6addacfe1dd8b420f3ec7b0dde1954c59858bc8e6d (from https://pypi.org/simple/operator-courier/), version: 2.0.1
    Skipping link https://files.pythonhosted.org/packages/67/18/20d0f6ccac41906cf87d4f55f1a5d2b0104ad5ab650e7287f783630fb292/operator_courier-2.0.1-py2-none-any.whl#sha256=492d51c4edddb9b20bc5b802b5e5cf8a0f71a46e899b736fc03ca59e3dd88432 (from https://pypi.org/simple/operator-courier/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/7b/e7/635b8761b142cff2c7bcf0a3ca54f780e5b05b1f67489f9e4685594ddf6f/operator-courier-2.0.2.tar.gz#sha256=fadb28597afde1deba8db57a660886b9105502c5f35077745eb1efdc18687731 (from https://pypi.org/simple/operator-courier/), version: 2.0.2
    Skipping link https://files.pythonhosted.org/packages/86/32/22f1b52d875be858beb709da303ee56c6dc04b28d82d6617661d88f7e277/operator_courier-2.0.2-py2-none-any.whl#sha256=3e1eeb6111df48ef67b45ec75b203ff3d7cc02a6c5b55714577e7a7d8c4625af (from https://pypi.org/simple/operator-courier/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/b4/b5/1f9927e4ba9b9f191c9817ec68b4a44ef88b122f8d4f4fd241a1f6f14ba3/operator-courier-2.0.3.tar.gz#sha256=b23da587a3ea961d3474c66f889b81e1cb529ab36ea31090fb568609a49f9c36 (from https://pypi.org/simple/operator-courier/), version: 2.0.3
    Skipping link https://files.pythonhosted.org/packages/a2/7d/82f66d6b287ab5e0ee7dd3ad5c1d12a94678a24efa722152040d0371c0b2/operator_courier-2.0.3-py2-none-any.whl#sha256=8d8233e6c2495ade885c9ff2d1c4d2480554b32c6f7c5f3cd473189a5abddf82 (from https://pypi.org/simple/operator-courier/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/ea/21/6c98531a2c6727900df8d0884478ada7a24aec62a54f4992a9a60c9467b3/operator-courier-2.1.0.tar.gz#sha256=5ab9c96867a04271a1cbea9f6a5a09a641c0443167a99762a8d25f5dbdb7a47a (from https://pypi.org/simple/operator-courier/), version: 2.1.0
    Skipping link https://files.pythonhosted.org/packages/54/b5/9ab04d61930945c34d932f3240c9daa7524eefd70538dcde655a021e6464/operator_courier-2.1.0-py2-none-any.whl#sha256=312c6ecf57b9e52cc562a43c7bcd885c84178a1910dfd4e8719bb7afdd355cca (from https://pypi.org/simple/operator-courier/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/b1/54/4985170655fa467038657ab4d5fcc33cd9fa118057897f09ab73af15aa10/operator-courier-2.1.1.tar.gz#sha256=acfe577ce7b098af28d99e2f9d1d5d8cb8d722950b8921308865220a7071ec9f (from https://pypi.org/simple/operator-courier/), version: 2.1.1
    Skipping link https://files.pythonhosted.org/packages/76/86/95c041566d4d18e62e529e3983a4cbcb8ea877b4ffc7bb53cdd17f7d0aee/operator_courier-2.1.1-py2-none-any.whl#sha256=afea8c613609d7eacf1863440b96603fefd2b170ac78c1b2ffcd5fd5e676b074 (from https://pypi.org/simple/operator-courier/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/0d/9d/3605e6892920f952ac1a1351cc01c5aac284f966d83f461aaf20498d4a50/operator-courier-2.1.2.tar.gz#sha256=7e3b643c6deddd2b5e6c5c2f509366a7c61121e9485a7795cb8b77f8794f2912 (from https://pypi.org/simple/operator-courier/), version: 2.1.2
    Found link https://files.pythonhosted.org/packages/58/3f/3225e51c96f47e0ae3a387b38db0a10551c787200c0d1778dc256e91d75d/operator_courier-2.1.2-py3-none-any.whl#sha256=fcae352fc518337647c24aa318d907d3767cba55587d9339d682fc4a361bb27b (from https://pypi.org/simple/operator-courier/), version: 2.1.2
    Found link https://files.pythonhosted.org/packages/b0/99/3aaad928d82fdd8a1542e6deb9d439bd11473f1199dab71428f45c436407/operator-courier-2.1.3.tar.gz#sha256=1c6ec5ae7de7cf15e987ee0b5dd1c6579493ebbebaef566d59eb5ed242addd9d (from https://pypi.org/simple/operator-courier/), version: 2.1.3
    Skipping link https://files.pythonhosted.org/packages/f8/ec/dea9985227e86f43843ad8a8340043d3b0c86a5e697875c2fdc7fc75a832/operator_courier-2.1.3-py2-none-any.whl#sha256=5ff3ed599ef440e23bb88dee262ebd63878e7b0522c2b1ee6252ad7a2f097e90 (from https://pypi.org/simple/operator-courier/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/1c/dd/643f24658119642f0cd4c89d119698aabf8c4331025bcd449e3d1dcabb1b/operator-courier-2.1.4.tar.gz#sha256=50a81795579af9a9c2e773e60603b65300833e62d54f261ff44c2d22d8f34c6a (from https://pypi.org/simple/operator-courier/), version: 2.1.4
    Skipping link https://files.pythonhosted.org/packages/88/31/9031ddf99c7a1f1a1bc8c9fb3e4a1a8da1ad96ac3caeedecac7ed7bb0e1e/operator_courier-2.1.4-py2-none-any.whl#sha256=a4876f500aac241159279d86effafa575d703f2316d0c589b5bce004b17e8de5 (from https://pypi.org/simple/operator-courier/); it is not compatible with this Python
    Found link https://files.pythonhosted.org/packages/1f/58/31ef329e9cae1740da25b3b38ef3011fa94ce55bec2fcdfe69f454f4796d/operator-courier-2.1.5.tar.gz#sha256=27d6ead403df6b6ada9f9aff0eab0b8ef4d729e39603335a93f15f1146de4872 (from https://pypi.org/simple/operator-courier/), version: 2.1.5
    Found link https://files.pythonhosted.org/packages/8b/68/9e5db437dfdde3ad5aa230e822ed2a7de7b05e9bc855e624204ff0a02066/operator_courier-2.1.5-py3-none-any.whl#sha256=c6293b0f91ae5e7169cd0657b2321770d8984c2f82415ec70ca6afdd4eb2daa2 (from https://pypi.org/simple/operator-courier/), version: 2.1.5
    Found link https://files.pythonhosted.org/packages/cd/09/a4cedfe556575e288663c2fc57bafb5b7c9a986a887c86c330f749b40d57/operator-courier-2.1.6.tar.gz#sha256=7b43493d78e0f691a48abe3fc18ed0dee6dd20a254e8ab131a2b66faa0cab073 (from https://pypi.org/simple/operator-courier/), version: 2.1.6
    Found link https://files.pythonhosted.org/packages/43/17/26ac48a493952b90b54660917b566c50b3af7f3331b94a3f0949748b82c2/operator_courier-2.1.6-py3-none-any.whl#sha256=c2cc34960c25e32914a4933fadb2c6f7d1dab6c6ccf63aef5e84e9ed0e2edbdd (from https://pypi.org/simple/operator-courier/), version: 2.1.6
    Found link https://files.pythonhosted.org/packages/c4/fb/98db989367487447451b00ee0f0661e2ec164c565224c6064e30962f18f6/operator-courier-2.1.7.tar.gz#sha256=ca11468f78577c3179e986ce4e3b7d15e34b57ed0d4bd2e3fbcfc00da2d0f2ef (from https://pypi.org/simple/operator-courier/), version: 2.1.7
    Found link https://files.pythonhosted.org/packages/8a/3b/c8f3d95ee79a2d4992895b715095fcadeca7145f0b8fd7e5b9dd0ceecf24/operator_courier-2.1.7-py3-none-any.whl#sha256=06924ef57a12ac43e86f6dd3dd6ac2b896a36809a8e7c906128d78ffb07da98c (from https://pypi.org/simple/operator-courier/), version: 2.1.7
  Using version 2.1.7 (newest of versions: 0.0.1, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7)
  Using cached https://files.pythonhosted.org/packages/8a/3b/c8f3d95ee79a2d4992895b715095fcadeca7145f0b8fd7e5b9dd0ceecf24/operator_courier-2.1.7-py3-none-any.whl
  Downloading from URL https://files.pythonhosted.org/packages/8a/3b/c8f3d95ee79a2d4992895b715095fcadeca7145f0b8fd7e5b9dd0ceecf24/operator_courier-2.1.7-py3-none-any.whl#sha256=06924ef57a12ac43e86f6dd3dd6ac2b896a36809a8e7c906128d78ffb07da98c (from https://pypi.org/simple/operator-courier/)
Requirement already satisfied (use --upgrade to upgrade): pyyaml in /usr/local/lib/python3.5/dist-packages (from operator-courier)
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/local/lib/python3.5/dist-packages (from operator-courier)
Requirement already satisfied (use --upgrade to upgrade): semver in /usr/local/lib/python3.5/dist-packages (from operator-courier)
Requirement already satisfied (use --upgrade to upgrade): validators in /usr/local/lib/python3.5/dist-packages (from operator-courier)
Requirement already satisfied (use --upgrade to upgrade): idna<2.9,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests->operator-courier)
Requirement already satisfied (use --upgrade to upgrade): chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests->operator-courier)
Requirement already satisfied (use --upgrade to upgrade): urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests->operator-courier)
Requirement already satisfied (use --upgrade to upgrade): certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests->operator-courier)
Requirement already satisfied (use --upgrade to upgrade): decorator>=3.4.0 in /usr/local/lib/python3.5/dist-packages (from validators->operator-courier)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /usr/local/lib/python3.5/dist-packages (from validators->operator-courier)
Installing collected packages: operator-courier
  *** Error compiling '/tmp/pip-build-h23pi72p/operator-courier/operatorcourier/flatten.py'...
    File "/tmp/pip-build-h23pi72p/operator-courier/operatorcourier/flatten.py", line 65
      file_paths_to_copy.append((csv_path, f'{basename}-v{version}{ext}'))
                                                                       ^
  SyntaxError: invalid syntax

  *** Error compiling '/tmp/pip-build-h23pi72p/operator-courier/operatorcourier/nest.py'...
    File "/tmp/pip-build-h23pi72p/operator-courier/operatorcourier/nest.py", line 127
      csv_path = os.path.join(csv_folder, f'{csv_name}.clusterserviceversion.yaml')
                                                                                 ^
  SyntaxError: invalid syntax


  changing mode of /usr/local/bin/operator-courier to 755
Successfully installed operator-courier-2.1.7
Cleaning up...
Converted retries value: Retry(total=0, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=0, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
Converted retries value: Retry(total=0, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=0, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
You are using pip version 8.1.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@gyliu-dev1:~#
```

**Comment by gyliu513** [comment]
But I do install successfully on my macos, and it works well.

**Comment by StykMartin** [comment]
The best practice here should save time.
`pip install -U pip`. After this, you can't install operator-courier package via `pip`.

**Comment by MartinBasti** [comment]
> But I do install successfully on my macos, and it works well.

so your macos has py3.6 hasn't it?

**Comment by gyliu513** [comment]
@MartinBasti Yes, macos using py3.6, and it works well.

@StykMartin I had some trouble updating pip in my Ubuntu, still fixing.

But I think in the document, we should highlight python version as Prerequisites ;-)

**Comment by gyliu513** [comment]
@MartinBasti this is my macos

```
bogon:~ guangyaliu$ pip3 install operator-courier
Requirement already satisfied: operator-courier in /usr/local/lib/python3.7/site-packages (2.1.7)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.7/site-packages (from operator-courier) (5.2)
Requirement already satisfied: semver in /usr/local/lib/python3.7/site-packages (from operator-courier) (2.9.0)
Requirement already satisfied: validators in /usr/local/lib/python3.7/site-packages (from operator-courier) (0.14.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/site-packages (from operator-courier) (2.22.0)
Requirement already satisfied: six>=1.4.0 in ./Library/Python/3.7/lib/python/site-packages (from validators->operator-courier) (1.12.0)
Requirement already satisfied: decorator>=3.4.0 in /usr/local/lib/python3.7/site-packages (from validators->operator-courier) (4.4.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests->operator-courier) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests->operator-courier) (1.25.7)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests->operator-courier) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests->operator-courier) (2019.11.28)
bogon:~ guangyaliu$
```

**Comment by MartinBasti** [comment]
Maintainers should remove broken releases (up to 1.3.0) from PyPI and you should upgrade your pip

**Comment by StykMartin** [comment]
This is really a pitty that I can't run it on enterprise Python 2.4.

**Comment by kevinrizza** [comment]
> This is really pity that I can't run it on enterprise Python 2.4.

Python 2.x

**Comment by sonfrai223** [comment]
Operator-courier is a tool used to manage the distribution of Kubernetes Operators, so it is important that it functions properly. Here are some troubleshooting steps you can try:

Check that operator-courier is installed correctly: Make sure that operator-courier is installed and configured correctly on your system. You can check this by running the command "operator-courier --help" in your terminal.

Check that the correct version of operator-courier is installed: Make sure that you have installed the correct version of operator-courier for your operating system and the version of the Kubernetes Operator that you are using.

Check your network connection: Make sure that you have a stable internet connection and that your firewall settings are not blocking the connection. https://resijnt.id/

Check your credentials: If you are trying to access a private repository, make sure that your credentials are correct and that you have permission to access the repository.

If none of these steps resolve the issue, you may want to reach out to the operator-courier community or support team for further assistance.
